
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: CrossCompute
  username: postgres
  password: "bird0072"

test:
  <<: *default
  database: myapp_test



production:
  <<: *default
  database: myapp_production
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
